#pragma once

#define PINE 0
#define BIRCH 1
#define ROWAN 2

#define PINE_MAX_RADIUS "10"
#define BIRCH_MAX_RADIUS "8"
#define ROWAN_MAX_RADIUS "4"

#define PINE_GROWTH_FACTOR "0.2"
#define BIRCH_GROWTH_FACTOR "0.5"
#define ROWAN_GROWTH_FACTOR "0.2"

#define PINE_SHADE_TOLERANCE 0.3f
#define BIRCH_SHADE_TOLERANCE 0.1f
#define ROWAN_SHADE_TOLERANCE 0.3f

#define PINE_LONGEVITY 0.95f
#define BIRCH_LONGEVITY 0.7f
#define ROWAN_LONGEVITY 0.8f

#define PINE_PROPAGATION_MAX_RADIUS 30.0f
#define BIRCH_PROPAGATION_MAX_RADIUS 40.0f
#define ROWAN_PROPAGATION_MAX_RADIUS 50.0f
